version: "2"
linters:
  default: standard
  enable:
    - bodyclose
    - copyloopvar
    - errcheck
    - errname
    - exhaustive
    - gocritic
    - godot
    - gomodguard
    - gosec
    - govet
    - importas
    - ineffassign
    - misspell
    - prealloc
    - revive
    - staticcheck
    - unparam
    - unused
    - whitespace
  settings:
    exhaustive:
      default-signifies-exhaustive: true
    importas:
      alias:
        - pkg: k8s.io/api/core/v1
          alias: corev1
        - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
          alias: metav1
      no-unaliased: true
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - gosec
        path: (_test\.go|testing\.go|testsupport|e2etests)
      - linters:
          - unparam
        path: internal/mocks
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
